name: ai_bot
description: "An AI-powered chat bot that leverages Google's Gemini model to provide real-time responses. The app features a user-friendly interface where users can send messages and receive instant replies. It utilizes state management to handle message flows and ensure a smooth user experience. The app also includes error handling and UI feedback to enhance usability."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_generative_ai:
  flutter_bloc:
  bloc:
  equatable:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
